/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Orphan;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author iCode
 */
public class frmIntake extends javax.swing.JFrame {

  
    
    private static final String Username="root";
    private static final String Password="";
    private static final String ConnString="jdbc:mysql://localhost/orphanage";
    private Connection conn = null;
    private Statement st;
//    String[][]data1 = new String[200][8];

    
    
    
    
    
    public frmIntake() {
        initComponents();
//initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, 
         dim.height/2-this.getSize().height/2); 


    }

     public void connect()
     {
        try{
            conn=DriverManager.getConnection(ConnString,Username,Password);
            st = conn.createStatement();
        } 
            catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.toString());
        }
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        txtSur = new javax.swing.JTextField();
        cmbTime = new javax.swing.JComboBox<String>();
        cmbState = new javax.swing.JComboBox<String>();
        mm = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtOther = new javax.swing.JTextField();
        txtLGA = new javax.swing.JTextField();
        dd = new javax.swing.JComboBox<String>();
        cmbNation = new javax.swing.JComboBox<String>();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<String>();
        yyyy = new javax.swing.JComboBox<String>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Local Govt.:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Other Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Founded:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Area Founded:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time Founded:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Age:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nationality:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("State:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Intake ID. No.:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        txtID.setText(" ");
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("New Intake Registration");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("First Name:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 20, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 50));

        txtAge.setText(" ");
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 50, -1));

        txtFirst.setText(" ");
        jPanel1.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, -1));

        txtSur.setText(" ");
        jPanel1.add(txtSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 190, -1));

        cmbTime.setMaximumRowCount(12);
        cmbTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select...", "12:01am - 12:30am", "12:31am - 01:00am", "01:01am - 01:30am", "01:31am - 02:00am", "02:01am - 02:30am", "02:31am - 03:00am", "03:01am - 03:30am", "03:31am - 04:00am", "04:00am - 04:30am", "04:31am - 05:00am", "05:01am - 05:30am", "05:31am - 06:00am", "06:01am - 06:30am", "06:31am - 07:00am", "07:01am - 07:30am", "07:31am - 08:00am", "08:01am - 08:30am", "08:31am - 09:00am", "19:00am - 09:30am", "09:31am- 1 0:00am", "10:01am - 10:30am", "10:31am - 11:00am", "11:01am - 11:30am", "11:31am - 12:00pm", "12:01pm - 12:30pm", "12:31pm - 01:00pm", "01:01pm - 01:30pm", "01:31pm - 02:00pm", "02:01pm - 02:30pm", "02:31pm - 03:00pm", "03:01pm - 03:30pm", "03:31pm - 04:00pm", "04:00pm - 04:30pm", "04:31pm - 05:00pm", "05:01pm - 05:30pm", "05:31pm - 06:00pm", "06:01pm - 06:30pm", "06:31pm - 07:00pm", "07:01pm - 07:30pm", "07:31pm - 08:00pm", "08:01pm - 08:30pm", "08:31pm - 09:00pm", "19:00pm - 09:30pm", "09:31pm- 1 0:00pm", "10:01pm - 10:30pm", "10:31pm - 11:00pm", "11:01pm - 11:30pm", "11:31pm - 12:00pm" }));
        jPanel1.add(cmbTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 150, -1));

        cmbState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select....", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara" }));
        jPanel1.add(cmbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 200, -1));

        mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 40, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, 80));

        txtOther.setText(" ");
        jPanel1.add(txtOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, -1));

        txtLGA.setText(" ");
        jPanel1.add(txtLGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 170, -1));

        dd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 40, -1));

        cmbNation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Nigerian", "Non-Nigerian" }));
        jPanel1.add(cmbNation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 170, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 610, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Surname:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Male", "Female" }));
        jPanel1.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 100, -1));

        yyyy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel1.add(yyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 60, -1));

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jButton5.setText("Save Record");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

txtID.setText("");
txtFirst.setText("");
txtSur.setText("");
txtOther.setText("");
txtArea.setText("");
cmbTime.setSelectedItem("");
txtAge.setText("");
cmbGender.setSelectedItem("");
cmbNation.setSelectedItem("");
cmbState.setSelectedItem("");
txtLGA.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        this.show(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(" ".equals(txtID.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
    
      if(" ".equals(txtFirst.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      
      if(" ".equals(txtSur.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      if(" ".equals(txtOther.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      if(" ".equals(txtArea.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      
      if(" ".equals(cmbTime.getSelectedItem()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }

      if(" ".equals(txtAge.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      
      if(" ".equals(cmbGender.getSelectedItem()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      
      if(" ".equals(cmbNation.getSelectedItem()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }
      
      if(" ".equals(cmbState.getSelectedItem()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }

      if(" ".equals(txtLGA.getText()))
      {
            JOptionPane.showMessageDialog(this,"Please Enter Registration Number");
            return;
      }

                    String InStatus = "Charge";
                    String Datefound= dd.getSelectedItem()+"/"+ mm.getSelectedItem()+"/"+yyyy.getSelectedItem();
            try
            {

                        String Query="INSERT INTO INTAKE(IDNO,FIRSTNAME,LASTNAME,OTHERNAME,DATEFOUND,AREA,TIME,AGE,GENDER,NATIONALITY,STATE,LGA,STATUS)\n" +
                        "VALUES('" + txtID.getText()
                        +"'," + "'"+txtFirst.getText()
                        +"'," + "'"+txtSur.getText()
                        +"'," + "'"+txtOther.getText()
                        +"'," + "'"+Datefound
                        + "'," + "'"+ txtArea.getText()
                        + "'," + "'"+cmbTime.getSelectedItem()
                        + "'," + "'"+ txtAge.getText()
                        + "'," + "'"+cmbGender.getSelectedItem()
                        + "'," + "'"+cmbNation.getSelectedItem()
                        + "'," + "'"+cmbState.getSelectedItem()
                        + "'," + "'"+txtLGA.getText()
                        + "'," + "'"+InStatus
                        +"')";
                        connect();   
                        st.execute(Query);
                        JOptionPane.showMessageDialog(this,"New Intake Record Succefully Saved","Success Message",JOptionPane.INFORMATION_MESSAGE);

                      //  Get_Data();
           }
           catch(SQLException ex)
           {
                JOptionPane.showMessageDialog(this, ex.toString());
           }


// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIntake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbNation;
    private javax.swing.JComboBox<String> cmbState;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JComboBox<String> dd;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mm;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLGA;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtSur;
    private javax.swing.JComboBox<String> yyyy;
    // End of variables declaration//GEN-END:variables
}
